package com.rsr41.oracle.domain.model

data class TarotCard(
    val id: Int,
    val nameKo: String,
    val nameEn: String,
    val keywordKo: String,
    val keywordEn: String,
    val meaningUpright: String,
    val meaningReversed: String
)

object TarotData {
    // 0-21: Major Arcana (Classic)
    // 22-35: Minor Arcana / Custom (MVP)
    val cards = listOf(
        // Major Arcana (0-21)
        TarotCard(0, "광대", "The Fool", "새로운 시작", "New Beginnings", 
            "순수한 시작, 자유로운 영혼, 무한한 가능성을 의미합니다. 두려움 없이 첫 발을 내딛으세요.", 
            "계획 없는 시작, 무모함, 경솔한 행동을 주의해야 합니다."),
        TarotCard(1, "마법사", "The Magician", "창조와 능력", "Creation & Power", 
            "모든 준비는 끝났습니다. 당신의 재능을 발휘하여 목표를 달성하세요.", 
            "속임수, 재능의 낭비, 소통의 부재를 경계하세요."),
        TarotCard(2, "여사제", "The High Priestess", "직관과 지혜", "Intuition", 
            "내면의 목소리에 귀 기울이세요. 지혜와 통찰력이 필요한 시기입니다.", 
            "감정적 억압, 비밀의 폭로, 내면의 갈등을 주의하세요."),
        TarotCard(3, "여황제", "The Empress", "풍요와 사랑", "Fertility", 
            "물질적/정신적 풍요가 찾아옵니다. 사랑과 포용의 힘을 믿으세요.", 
            "과도한 사치, 게으름, 정서적 불안을 조심하세요."),
        TarotCard(4, "황제", "The Emperor", "권위와 질서", "Authority", 
            "체계적이고 현실적인 접근이 필요합니다. 리더십을 발휘하여 안정을 찾으세요.", 
            "독단적인 태도, 권위주의, 융통성 부족이 문제가 될 수 있습니다."),
        TarotCard(5, "교황", "The Hierophant", "전통과 조언", "Tradition", 
            "주변의 조언을 구하거나 전통적인 방식을 따르는 것이 좋습니다. 배움의 시기입니다.", 
            "맹목적인 믿음, 독선, 관습에 얽매이는 것을 피하세요."),
        TarotCard(6, "연인", "The Lovers", "선택과 조화", "Love & Harmony", 
            "중요한 선택의 기로에 있습니다. 조화롭고 협력적인 관계가 핵심입니다.", 
            "잘못된 선택, 불화, 유혹에 흔들리는 마음을 주의하세요."),
        TarotCard(7, "전차", "The Chariot", "승리와 전진", "Victory", 
            "강한 의지로 목표를 향해 돌진하세요. 장애물을 극복하고 성취할 것입니다.", 
            "통제 불능, 무모한 폭주, 패배감을 경계해야 합니다."),
        TarotCard(8, "힘", "Strength", "인내와 용기", "Strength", 
            "부드러움이 강함을 이깁니다. 내면의 인내심으로 상황을 통제하세요.", 
            "자만심, 통제 상실, 나약한 마음을 다스려야 합니다."),
        TarotCard(9, "은둔자", "The Hermit", "성찰과 탐구", "Introspection", 
            "잠시 멈춰 내면을 돌아볼 시간입니다. 스스로 답을 찾는 고독이 필요합니다.", 
            "고립, 외톨이, 지나친 신중함으로 기회를 놓치지 마세요."),
        TarotCard(10, "운명의 수레바퀴", "Wheel of Fortune", "변화와 기회", "Destiny", 
            "새로운 운의 흐름이 시작됩니다. 변화를 받아들이고 기회를 잡으세요.", 
            "뜻밖의 불운, 저항할 수 없는 변화, 반복되는 실수에 주의하세요."),
        TarotCard(11, "정의", "Justice", "공정과 균형", "Justice", 
            "객관적이고 공정한 판단이 필요합니다. 뿌린 대로 거두는 시기입니다.", 
            "편견, 불공정, 우유부단함으로 인한 손해를 조심하세요."),
        TarotCard(12, "매달린 사람", "The Hanged Man", "희생과 관점", "Sacrifice", 
            "새로운 관점으로 세상을 보면 답이 보입니다. 잠시 멈춤의 미학을 배우세요.", 
            "헛된 희생, 고집, 정체된 상황에 갇혀있을 수 있습니다."),
        TarotCard(13, "죽음", "Death", "종결과 시작", "Transformation", 
            "낡은 것을 버려야 새것이 옵니다. 대대적인 변화를 두려워하지 마세요.", 
            "변화에 대한 두려움, 미련, 정체된 상황을 경계하세요."),
        TarotCard(14, "절제", "Temperance", "중용과 조화", "Balance", 
            "극단을 피하고 균형을 맞추세요. 인내심을 가지고 천천히 나아가야 합니다.", 
            "불균형, 과도한 욕심, 조급함이 일을 그르칠 수 있습니다."),
        TarotCard(15, "악마", "The Devil", "구속과 욕망", "Addiction", 
            "물질적 유혹이나 나쁜 습관에 얽매여 있지 않은지 돌아보세요.", 
            "집착, 중독, 억압된 상황에서 벗어나야 합니다."),
        TarotCard(16, "탑", "The Tower", "붕괴와 변화", "Disaster", 
            "갑작스러운 변화가 있지만, 이는 더 튼튼한 기반을 만들기 위함입니다.", 
            "재난, 파괴, 충격적인 사건에 대비하고 마음을 굳게 먹으세요."),
        TarotCard(17, "별", "The Star", "희망과 영감", "Hope", 
            "어둠 끝에 희망이 보입니다. 당신의 꿈과 직관을 믿으세요.", 
            "실망, 비관, 헛된 꿈에 빠지지 않도록 현실감각을 유지하세요."),
        TarotCard(18, "달", "The Moon", "불안과 환상", "Illusion", 
            "보이지 않는 불안감이 있지만 직관을 믿고 나아가면 진실을 찾을 것입니다.", 
            "혼란, 기만, 막연한 공포에 압도되지 마세요."),
        TarotCard(19, "태양", "The Sun", "성공과 활력", "Success", 
            "모든 것이 밝게 빛납니다. 긍정적인 에너지와 성공이 함께할 것입니다.", 
            "자만심, 허세, 일시적인 성공에 안주하지 마세요."),
        TarotCard(20, "심판", "Judgement", "부활과 보상", "Awakening", 
            "과거의 노력에 대한 보상을 받을 때입니다. 중요한 결단이 필요합니다.", 
            "후회, 우유부단, 과거에 얽매여 나아가지 못하는 것을 주의하세요."),
        TarotCard(21, "세계", "The World", "완성과 통합", "Completion", 
            "하나의 여정이 성공적으로 끝났습니다. 완벽한 조화와 결실을 누리세요.", 
            "미완성, 정체, 완벽주의로 인한 지연을 경계하세요."),
            
        // Minor Arcana (Cups placeholder logic for MVP - representing Emotions)
        TarotCard(22, "컵 에이스", "Ace of Cups", "새로운 감정", "Love Beginnings", 
            "새로운 사랑이나 감정의 시작을 알립니다. 마음을 여세요.", "감정의 메마름, 억눌린 마음."),
        TarotCard(23, "컵 2", "Two of Cups", "결합과 파트너십", "Partnership", 
            "서로 마음이 통하는 파트너를 만납니다. 조화로운 관계입니다.", "관계의 불화, 오해."),
        TarotCard(24, "컵 3", "Three of Cups", "축하와 어울림", "Celebration", 
            "주변 사람들과 즐거운 시간을 보냅니다. 기쁨을 나누세요.", "의존, 과도한 유흥."),
        TarotCard(25, "컵 10", "Ten of Cups", "행복한 가정", "Happiness", 
            "가족이나 모임에서 평화와 행복을 느낍니다. 정서적 만족감이 큽니다.", "가정 불화, 깨진 평화."),

        // Minor Arcana (Wands placeholder logic for MVP - representing Action)
        TarotCard(26, "완드 에이스", "Ace of Wands", "열정과 시작", "Inspiration", 
            "새로운 일에 대한 영감이 떠오릅니다. 열정을 가지고 시작하세요.", "의욕 상실, 지연."),
        TarotCard(27, "완드 4", "Four of Wands", "안정과 환영", "Stability", 
            "평화롭고 안정적인 시기입니다. 휴식을 취하거나 축하할 일이 생깁니다.", "불안정, 불화."),
        TarotCard(28, "완드 8", "Eight of Wands", "신속한 진행", "Speed", 
            "일이 빠르게 진행됩니다. 흐름을 타고 목표를 향해 나아가세요.", "성급함, 실수."),
        TarotCard(29, "완드 10", "Ten of Wands", "부담과 책임", "Burden", 
            "책임감이 무겁지만 끝이 보입니다. 조금만 더 힘을 내세요.", "과로, 압박감으로 인한 포기."),

        // Minor Arcana (Swords placeholder logic for MVP - representing Intellect/Conflict)
        TarotCard(30, "소드 에이스", "Ace of Swords", "승리와 결단", "Clarify", 
            "명확한 사고로 문제를 해결합니다. 과감한 결단이 필요합니다.", "혼란, 잘못된 판단."),
        TarotCard(31, "소드 3", "Three of Swords", "상처와 슬픔", "Heartbreak", 
            "마음의 상처가 있지만 이는 치유를 위한 과정입니다. 감정을 인정하세요.", "지나친 비관, 회복 거부."),
        TarotCard(32, "소드 10", "Ten of Swords", "고통의 끝", "Ruin", 
            "힘든 시기가 완전히 끝났습니다. 이제 다시 일어서는 일만 남았습니다.", "절망, 끝없는 고통."),

        // Minor Arcana (Pentacles placeholder logic for MVP - representing Material)
        TarotCard(33, "펜타클 에이스", "Ace of Pentacles", "금전적 기회", "Abundance", 
            "새로운 금전적 기회나 풍요가 찾아옵니다. 현실적인 성취를 이룹니다.", "기회 상실, 탐욕."),
        TarotCard(34, "펜타클 5", "Five of Pentacles", "궁핍과 고난", "Hardship", 
            "어려운 시기일 수 있지만 도움의 손길은 가까이에 있습니다.", "고립, 절망적 빈곤."),
        TarotCard(35, "펜타클 10", "Ten of Pentacles", "부유와 유산", "Wealth", 
            "물질적인 풍요와 안정을 누립니다. 가문의 번영을 의미하기도 합니다.", "돈 문제로 인한 다툼.")
    )
}
