name: OracleIOS
options:
  bundleIdPrefix: com.rsr41.oracle
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top
  developmentLanguage: ko
  knownRegions:
    - Base
    - ko
    - en

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    SWIFT_EMIT_LOC_STRINGS: YES
    ENABLE_TESTABILITY: YES

targets:
  OracleIOS:
    type: application
    platform: iOS
    sources:
      - path: OracleIOS
        excludes:
          - "**/.DS_Store"
          - "**/Resources/**"
    resources:
      - path: OracleIOS/Resources
        buildPhase: resources
      - path: OracleIOS/Resources/en.lproj/Localizable.strings
        buildPhase: resources
        type: file
      - path: OracleIOS/Resources/ko.lproj/Localizable.strings
        buildPhase: resources
        type: file
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rsr41.oracle.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        INFOPLIST_KEY_CFBundleDisplayName: Oracle
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UIUserInterfaceStyle: Light
        SWIFT_STRICT_CONCURRENCY: complete

  OracleIOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OracleIOSTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: OracleIOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rsr41.oracle.ios.tests
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OracleIOS.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/OracleIOS"

schemes:
  OracleIOS:
    build:
      targets:
        OracleIOS: all
        OracleIOSTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - OracleIOSTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
